server:
  port: 8081
spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/mi_db?authSource=admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
